GPU: '0'
b1: 0.5
b2: 0.999
batch_size: 1
datasets_folder: DataForPytorch
datasets_path: datasets
fmap: 16
gap_h: 75
gap_s: 75
gap_w: 75
img_h: 150
img_s: 150
img_w: 150
lr: 5.0e-05
n_epochs: 30
normalize_factor: 1
output_dir: ./results
train_datasets_size: 3500
